/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/CreateProxies/Card.vue')['default']
    CreateProxies: typeof import('./src/components/CreateProxies/index.vue')['default']
    Edit: typeof import('./src/components/ManageProxies/Edit.vue')['default']
    FrpcManager: typeof import('./src/components/FrpcManager.vue')['default']
    GetConf: typeof import('./src/components/ManageProxies/GetConf.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    Infomation: typeof import('./src/components/ManageProxies/Infomation.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Menu: typeof import('./src/components/ManageProxies/Menu.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NCode: typeof import('naive-ui')['NCode']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NFlex: typeof import('naive-ui')['NFlex']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    ProxyList: typeof import('./src/components/ProxyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
  }
}
