/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/CreateProxies/Card.vue')['default']
    CreateProxies: typeof import('./src/components/CreateProxies/index.vue')['default']
    CreateProxy: typeof import('./src/components/CreateProxy.vue')['default']
    Edit: typeof import('./src/components/ManageProxies/Edit.vue')['default']
    FrpcManager: typeof import('./src/components/FrpcManager.vue')['default']
    GetConf: typeof import('./src/components/ManageProxies/GetConf.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    Infomation: typeof import('./src/components/ManageProxies/Infomation.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Menu: typeof import('./src/components/ManageProxies/Menu.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NFlex: typeof import('naive-ui')['NFlex']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NModal: typeof import('naive-ui')['NModal']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ProxyList: typeof import('./src/components/ProxyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
  }
}
